services:
  db:
    image: postgres:latest
    container_name: postgres-docker
    environment:
      - POSTGRES_DATABASE=${DATABASE}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "10000:5432"
    restart: always
  app:
    depends_on:
      - db
    image: python-sprint5
    container_name: python-sprint5

    