services:
  db:
    image: postgres:latest
    container_name: postgresdocker
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    #ports:
     # - "10000:5432"
    restart: always
  app:
    depends_on:
      - db
    image: pythonsprint5:0.1.0
    container_name: pythonsprint5

    