services:
  db:
    image: mariadb:latest
    container_name: mariadb-docker
    environment:
      - MARIADB_DATABASE=${DATABASE}
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MARIADB_USER=${USER}
      - MARIADB_PASSWORD=${PASSWORD}
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"